### ISSUE TITLE
Fatal Error: Composer autoload file not found!

### ISSUE THREAD

**Issue by DACRepair** [WHSuite/whsuite#1]
I have been trying to install this for the better part of 2 hours now, and all I can seem to get WHSuite to do is display an error:
`Fatal Error: Composer autoload file not found!`

Specs:
Debian 8 (running in a Docker Container)
Apache2
php7.0
Ioncube 6.4

I have gone over and made sure that php has all the needed extensions installed, and that apache has rewrite turned on.

**Comment by DACRepair** [comment]
issue was solved by going into the `whsuite` folder and running `composer install` 
*note: composer will need to be installed. This is not mentioned in the docs.

**Comment by rickmills** [comment]
Hi Dac,

We're in the process of writing up manual install instructions, and will make sure that future full release zips are either "ready to go" with composer already run, or will provide better instructions. Things are still a little all over the place as the build process we previously used had to be reworked for the opensource release.

For now it's as you said, you clone/download the master branch and run `composer install` in the `master` branch.

Cheers
