### ISSUE TITLE
Fatal Error: Composer autoload file not found!

### ISSUE THREAD

**Issue by SamTheMan1456** [WHSuite/whsuite#14]
I keep getting this error whenever I go to my directory (.../pages/whmaster/www/). I run off of a control panel with

Apache version:	2.4.178
PHP version:	5.6.23
MySQL version:	5.6.30
Operating System	Linux
Kernel Version	3.2.40
Architecture	i686

**Comment by SamTheMan1456** [comment]
I can't run something off a command line through a control panel as seen in #11.

**Comment by rickmills** [comment]
Hi,

WHSuite cant be installed by directly uploading to a control panel. You'll need command line access to build your composer files as this is a modern php application.
