### ISSUE TITLE
Is dead?

### ISSUE THREAD

**Issue by paulohsrocha** [WHSuite/whsuite#21]
Is dead?

**Comment by rickmills** [comment]
Yes, we've not got any plans to do any updates, however would be happy to talk to any experienced developers out there who wish to take over the project and continue it as a free opensource billing system.

**Comment by paulohsrocha** [comment]
I candidate, if you can, call me by email or Whatsapp 31984258624
paulohsrocha@gmail.com

Paulo Henrique

Em 4 de ago de 2018 04:39, "Rick Mills" <notifications@github.com> escreveu:
